### ISSUE TITLE
How to have my printer URI pre selected

### ISSUE THREAD

**Issue by ArchGalileu** [emarsden/ipp-el#1]
Great package ;)

I have difficulties pasting the uri of the printer every time, can i make it permanent?

Best regards
ArchGalileu

**Comment by emarsden** [comment]
I'm glad the package is useful. 

I tried to implement your suggestion: please see the variable ipp-default-printer, which you can customize using 

    M-x customize-group RET ipp-printing RET

Then when you call ipp-print-file for example the default printer should be preselected in the minibuffer.

**Comment by ArchGalileu** [comment]
It gives the error when saving the URI on customize group

`custom-group-mark-to-save: Symbol’s value as variable is void: ipp://localhost:631/printers/Hewlett-Packard_HP_LaserJet_Professional_P_1102w_
`

Thank you for your pacience ;)

Best regards
ArchGalileu

**Comment by emarsden** [comment]
Hopefully fixed now!

**Comment by ArchGalileu** [comment]
Perfect @emarsden 

;)

Again congratulations 

Best regards
ArchGalileu
